# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c79d35487185b26149aec70b6345cefd"
name = "International Quote"
application_url = "https://int-quoter-production.up.railway.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_draft_orders,read_products"

[auth]
redirect_urls = ["https://int-quoter-production.up.railway.app/auth/callback", "https://int-quoter-production.up.railway.app/auth/shopify/callback", "https://int-quoter-production.up.railway.app/api/auth/callback"]

[app_proxy]
url = "https://int-quoter-production.up.railway.app"
subpath = "int-quoter"
prefix = "apps"

application_url = "https://int-quoter-production.up.railway.app"